set(CMAKE_SYSTEM_PROCESSOR sh4)

set(CMAKE_C_COMPILER /opt/toolchains/dc/kos/utils/gnu_wrappers/kos-cc)
set(CMAKE_CXX_COMPILER /opt/toolchains/dc/kos/utils/gnu_wrappers/kos-c++)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
